"""added travel model

Revision ID: 1c9cc52d0b8a
Revises: e3a965fc5221
Create Date: 2026-01-04 23:43:21.250169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9cc52d0b8a'
down_revision: Union[str, Sequence[str], None] = 'e3a965fc5221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travels_auth_id'), table_name='travels')
    op.create_index(op.f('ix_travels_auth_id'), 'travels', ['auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travels_auth_id'), table_name='travels')
    op.create_index(op.f('ix_travels_auth_id'), 'travels', ['auth_id'], unique=True)
    # ### end Alembic commands ###
