"""tickets

Revision ID: 439558f0592f
Revises: 3b696bf389b6
Create Date: 2026-01-10 02:26:11.252375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '439558f0592f'
down_revision: Union[str, Sequence[str], None] = '3b696bf389b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'category',
               existing_type=postgresql.ENUM('BUG', 'FEATURE', 'DATA', 'OTHER', name='ticketcategory'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('support_tickets', 'priority',
               existing_type=postgresql.ENUM('LOW', 'HIGH', name='ticketpriority'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('LOW', 'HIGH', name='ticketpriority'),
               existing_nullable=False)
    op.alter_column('support_tickets', 'category',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('BUG', 'FEATURE', 'DATA', 'OTHER', name='ticketcategory'),
               existing_nullable=False)
    # ### end Alembic commands ###
