"""tickets

Revision ID: b39508abc5bc
Revises: 439558f0592f
Create Date: 2026-01-10 02:31:22.010969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39508abc5bc'
down_revision: Union[str, Sequence[str], None] = '439558f0592f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_auth_id'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_auth_id'), 'support_tickets', ['auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_auth_id'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_auth_id'), 'support_tickets', ['auth_id'], unique=True)
    # ### end Alembic commands ###
